resources:
  pipelines:
  - pipeline: EsgiProjetCI
    source: Esgi11.Projet-CI
trigger:
  branches:
    include:
      - main
stages:
  - stage: Staging
    jobs:
    - deployment: Deploy
      environment: Staging-Projet
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none
              - download: EsgiProjetCI
              - task: UsePythonVersion@0
                inputs:
                  versionSpec: '3.9'
                displayName: 'Use Python version'
              - task: AzureRmWebAppDeployment@4
                displayName: Deploy to Azure Web App
                inputs:
                  azureSubscription: esgi-tp
                  webAppName: esgi-devops11tp3-app
                  deployToSlotOrASE: true
                    slotName: staging
                    resourceGroupName: esgi-devops11-rg
                  package: $(Pipeline.Workspace)/EsgiProjetCI/$(Build.BuildId).zip

  - stage: Prod
    jobs:
    - deployment: Deploy
      environment: Prod-Projet
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none
              - download: EsgiProjetCI
              - task: UsePythonVersion@0
                inputs:
                  versionSpec: '3.9'
                displayName: 'Use Python version'
              - task: AzureRmWebAppDeployment@4
                displayName: Deploy to Azure Web App
                inputs:
                  azureSubscription: esgi-tp
                  webAppName: esgi-devops11tp3-app
                  resourceGroupName: esgi-devops11-rg
                  package: $(Pipeline.Workspace)/EsgiProjetCI/$(Build.BuildId).zip