resources:
  pipelines:
  - pipeline: EsgiPrjCI
    source: Esgi12.Prj-CI
trigger:
  branches:
    include:
      - main
stages:
  - stage: Staging
    jobs:
    - deployment: Deploy
      environment: Staging-Prj
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none
              - download: EsgiPrjCI
              - task: UsePythonVersion@0
                inputs:
                  versionSpec: '3.8'
                displayName: 'Use Python version'
              - task: AzureRmWebAppDeployment@4
                displayName: Deploy to Azure Web App
                inputs:
                  azureSubscription: esgi-tp
                  webAppName: esgi-devops12prj-app
                  deployToSlotOrASE: true
                  slotName: staging
                  resourceGroupName: esgi-devops12-rg
                  package: $(Pipeline.Workspace)/EsgiPrjCI/drop/$(Build.BuildId).zip

  - stage: Prod
    jobs:
    - deployment: Deploy
      environment: Prod-Prj
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none
              - download: EsgiPrjCI
              - task: UsePythonVersion@0
                inputs:
                  versionSpec: '3.8'
                displayName: 'Use Python version'
              - task: AzureRmWebAppDeployment@4
                displayName: Deploy to Azure Web App
                inputs:
                  azureSubscription: esgi-tp
                  webAppName: esgi-devops12prj-app
                  resourceGroupName: esgi-devops12-rg
                  package: $(Pipeline.Workspace)/EsgiPrjCI/drop/$(Build.BuildId).zip