trigger: none
stages:
- stage: Validate
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Install Python 3.8'
    
    - script: |
        python -m venv env
        env/Scripts/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install Flask
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: "Install requirements"

    - script: |
        env/Scripts/activate
        python build.py
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: "Download Model"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/Flaskfrontend.zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/Flaskfrontend.zip
      displayName: 'Upload package'
      artifact: Frontend
      